version: "3"

services:
  wordpress:
    container_name: wordpress
    build: .
    volumes:
      - ./wordpress:/var/www/wordpress

  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./site.conf:/etc/nginx/conf.d/default.conf

  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
